# Generated by Django 2.2 on 2019-08-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chocolate', 'chocolate'), ('strawberry', 'strawberry'), ('vanilla', 'vanilla'), ('cherry', 'cherry'), ('blueberry', 'blueberry'), ('peanut butter', 'peanut butter')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='icecream.Container')),
                ('scoops', models.ManyToManyField(to='icecream.Flavour')),
            ],
        ),
    ]
